### ISSUE TITLE
AutoRest Go: Using autorest to generate Go Clients fails when Specification file have empty version

### ISSUE THREAD

**Issue by Shwetap05** [Azure/azure-sdk-for-go#1199]
Using autorest to generate go client fails with below error if **version** in the specification json file is empty

Error:
FATAL: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.LastIndexOf(Char value, Int32 startIndex, Int32 count)
   at AutoRest.Go.Model.CodeModelGo.PackageVerDir() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\Model\CodeModelGo.cs:line 64
   at AutoRest.Go.Model.CodeModelGo.get_DefaultUserAgent() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\Model\CodeModelGo.cs:line 83
   at AutoRest.Go.Model.CodeModelGo.get_UserAgent() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\Model\CodeModelGo.cs:line 31
   at AutoRest.Go.Templates.VersionTemplate.<ExecuteAsync>d__1.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\obj\Razor\Templates\VersionTemplate.cshtml:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.<Write>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Go.CodeGeneratorGo.<Generate>d__6.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\CodeGeneratorGo.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Go.Program.<ProcessInternal>d__3.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\Program.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: go/generate - FAILED
FATAL: Error: Plugin go reported failure.
Process() cancelled due to exception : Plugin go reported failure.
  Error: Plugin go reported failure.

-------------------------------------------------------------------------------------------------------------------
Sample Json file, with empty version field that causes exception:
{
  "basePath": "/",
  "definitions": {},
  "host": "testhost",
  "info": {
    "title": "testAPI",
    "version": ""
  },
  "paths": {
    "/users/get": {
      "post": {
        "description": "",
        "operationId": "postUsersGet",
        "parameters": [],
        "responses": {
          "default": {
            "description": "Unexpected Error!"
          }
        },
        "summary": "Get user",
        "tags": [
          "Users"
        ]
      }
    }
  },
  "produces": [
    "application/json",
    "text/json",
    "application/xml",
    "text/xml"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0"
}

**Comment by jhendrixMSFT** [comment]
According to the OpenAPI 2.0 spec (which is what our generator supports) the version field is required.  But it seems that we shouldn't just throw an exception; there should be an good error message explaining the problem.  @fearthecowboy doesn't the modeler verify the spec before handing off to the generator?

**Comment by Shwetap05** [comment]
Yes looked at the spec but what was not clear was if the field should also not be empty b/c the document renders fine in swagger editor without any schema failures.

**Comment by jhendrixMSFT** [comment]
ping @fearthecowboy

**Comment by fearthecowboy** [comment]
Weird. I'd have thought that the schema validation step should have caught that, but it appears that the schema just requires the presence of the field, not that the value has to be longer than zero characters.

We can add this to the schema
