### ISSUE TITLE
graphrbac test fails with "Insufficient privileges to complete the operation"

### ISSUE THREAD

**Issue by valiparsa** [Azure/azure-sdk-for-go#15248]
### Bug Report

- path of package `graphrbac/1.6/graphrbac`
- SDK version `v48.0.0`
- output of `go version`
```
$ go test -v ./graphrbac/
2021/08/09 16:41:45 invalid value specified for AZURE_USE_DEVICEFLOW, disabling
=== RUN   ExampleCreateServicePrincipal
2021/08/09 16:41:46 graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2021-08-09T23:41:46","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"5e66bda4-0707-4249-84ff-9c14eddf58f9"}}]
--- FAIL: ExampleCreateServicePrincipal (0.59s)
panic: graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2021-08-09T23:41:46","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"5e66bda4-0707-4249-84ff-9c14eddf58f9"}}] [recovered]
	panic: graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2021-08-09T23:41:46","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"5e66bda4-0707-4249-84ff-9c14eddf58f9"}}]

goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc000133cb8, 0xc00051c540, 0x1b1, 0x23133ee3, 0x7b8980, 0xc0001ae0e0, 0xc000212800)
	/usr/lib/go-1.13/src/testing/example.go:89 +0x63f
testing.runExample.func2(0xc03c8d2e6054e081, 0x290dfb, 0xaadbe0, 0xc000010050, 0xc000010018, 0xc00001a420, 0xc000133cb8, 0xc000133ce8)
	/usr/lib/go-1.13/src/testing/run_example.go:58 +0x105
panic(0x7b8980, 0xc0001ae0e0)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
github.com/Azure-Samples/azure-sdk-for-go-samples/internal/util.LogAndPanic(0x862de0, 0xc0001ae0e0)
	/home/repositories/test/azure-sdk-for-go-samples/internal/util/util.go:18 +0x6a
github.com/Azure-Samples/azure-sdk-for-go-samples/graphrbac.ExampleCreateServicePrincipal()
	/home/repositories/test/azure-sdk-for-go-samples/graphrbac/graph_test.go:46 +0x4d1
testing.runExample(0x7ec209, 0x1d, 0x7ff828, 0x7f9f04, 0xae, 0x0, 0x0)
	/usr/lib/go-1.13/src/testing/run_example.go:62 +0x209
testing.runExamples(0xc000133e80, 0xaa6ca0, 0x2, 0x2, 0x7ffe1aeb0100)
	/usr/lib/go-1.13/src/testing/example.go:44 +0x1a8
testing.(*M).Run(0xc0000e2000, 0x0)
	/usr/lib/go-1.13/src/testing/testing.go:1118 +0x203
github.com/Azure-Samples/azure-sdk-for-go-samples/graphrbac.TestMain(0xc0000e2000)
	/home/repositories/test/azure-sdk-for-go-samples/graphrbac/graph_test.go:34 +0x143
main.main()
	_testmain.go:44 +0x135
FAIL	github.com/Azure-Samples/azure-sdk-for-go-samples/graphrbac	0.599s
FAIL


```

- What happened?
I cloned this repository `https://github.com/Azure-Samples/azure-sdk-for-go-samples` and executed go test for `graphrbac` package and it failed with this error: `Insufficient privileges to complete the operation`
- What did you expect or want to happen?
I expected all test function to run normally
- How can we reproduce it?
You can clone `https://github.com/Azure-Samples/azure-sdk-for-go-samples`, do the preparation which is documented in the README file and execute `go test -v ./graphrbac/`
- Anything we should know about your environment.
I'm running it with go version 1.13.8

```
go version go1.13.8 linux/amd64
```

**Comment by lirenhe** [comment]
Azure AD Graph API is now deprecated. We do not support SDK and sample fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
