### ISSUE TITLE
[azservicebus] panic() after 11,758,797 messages sent/received, after 3d19h

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-go#15736]
This process was running for 3d19h, with an artificial network outage every minute for 5 seconds.

021/10/06 14:17:26 Received: (p:11758797,r:0), Sent: 11759493, Errors: (p:0,r:0,s:2)

Prior to this we were in the process of recovering due to the connection being reported as `amqp: connection closed`. 

```
2021/10/06 14:17:31 [15922] END(sb.recover.client)
  revision=18
  requested=18
  newcr=18
2021/10/06 14:17:31 [15932] START(sb.recover.link)
2021/10/06 14:17:31 [15932] END(sb.recover.link)
2021/10/06 14:17:31 [15912] END(sb.recover.link)
  attempt=1
  recovery_kind=connection
  error=amqp: link closed
  error_type=*errors.errorString
2021/10/06 14:17:31 [15911] END(sb.recover)
  recover_attempt=1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x663b70]

goroutine 11935750 [running]:
github.com/Azure/azure-amqp-common-go/v3/rpc.(*Link).closeReceiver(0x0, {0x7c9a60, 0xc0002f6ab0})
  <gosource>/go/pkg/mod/github.com/!azure/azure-amqp-common-go/v3@v3.2.1/rpc/rpc.go:389 +0x90
github.com/Azure/azure-amqp-common-go/v3/rpc.(*Link).Close(0x6e8d60, {0x7c9a60, 0xc0002f6ab0})
  <gosource>/go/pkg/mod/github.com/!azure/azure-amqp-common-go/v3@v3.2.1/rpc/rpc.go:371 +0xc5
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/internal.(*mgmtClient).Close(0xc0013aeba0, {0x7c9a60, 0xc0002f6ab0})
  <sbsrc>/sdk/messaging/azservicebus/internal/mgmt.go:112 +0x9e
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/internal.(*amqpLinks).closeWithoutLocking(0xc000164000, {0x7c9a60, 0xc0002f6ab0}, 0xf)
  <sbsrc>/sdk/messaging/azservicebus/internal/amqpLinks.go:421 +0x5a5
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/internal.(*amqpLinks).recoverLink(0xc000164000, {0x7c9a60, 0xc000f5ec00}, 0x0)
  <sbsrc>/sdk/messaging/azservicebus/internal/amqpLinks.go:158 +0x648
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/internal.(*amqpLinks).recoverImpl(0xc0021ff800, {0x7c9a60, 0xc000f5ec00}, 0x1, 0x2c, {0x7c25a0, 0xc000010ce0})
  <sbsrc>/sdk/messaging/azservicebus/internal/amqpLinks.go:242 +0x7c5
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus/internal.(*amqpLinks).RecoverIfNeeded(0xc000164000, {0x7c99f0, 0xc00001c020}, 0xc005e581e0, {0x7c25a0, 0xc000010ce0})
  <sbsrc>/sdk/messaging/azservicebus/internal/amqpLinks.go:192 +0x271
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus.(*messageSettler).settleWithRetries(0xc0000659b0, {0x7c99f0, 0xc00001c020}, 0xc00001e1e0, 0xc000335e50)
  <sbsrc>/sdk/messaging/azservicebus/messageSettler.go:65 +0x15a
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus.(*messageSettler).CompleteMessage(0x7c99f0, {0x7c99f0, 0xc00001c020}, 0x14)
  <sbsrc>/sdk/messaging/azservicebus/messageSettler.go:77 +0x65
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus.(*Processor).processMessage(0xc000198410, {0x7c99f0, 0xc00001c020}, {0x7f7b1d2a1bc0, 0xc0048c3cc0}, 0xc0035dd8c0)
  <sbsrc>/sdk/messaging/azservicebus/processor.go:348 +0x185
github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus.(*Processor).subscribe.func1()
  <sbsrc>/sdk/messaging/azservicebus/processor.go:326 +0x78
created by github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus.(*Processor).subscribe
  <sbsrc>/sdk/messaging/azservicebus/processor.go:321 +0x208
```

**Comment by richardpark-msft** [comment]
With our simpler API (ReceiveMessages) we've now reached:
6d22h
2021/11/04 06:00:42 Received: (r:3739890), Sent: 3739899, Errors: (r:0,s:1)

Which is actually the entire time that was allocated for the test to run (it stops itself).

**Comment by richardpark-msft** [comment]
The panic was likely a result of a bad lock check around the management link recovery, which we fixed in https://github.com/Azure/azure-sdk-for-go/pull/16790.

**Comment by richardpark-msft** [comment]
Closing this issue.
