### ISSUE TITLE
[Doc][azsecrets] outdated code sample for Update Secret metadata

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-sdk-for-go#16495]
- What happened?
copy and paste code snippet from Update Secret metadata sample but it doesn't build

- What did you expect or want to happen?
correct code:
```diff
	properties := azsecrets.Properties{
		ContentType: &contentType,
		SecretAttributes: &azsecrets.Attributes{
			Enabled: to.BoolPtr(false),
		},
	}
	updateResp, err := client.UpdateSecretProperties(context.Background(), "secretName", properties, nil)
```

logging sample is also incorrect
![image](https://user-images.githubusercontent.com/7583839/145115722-8e009516-1345-472c-9ccc-2e2a52004d16.png)

**Comment by jeremymeng** [comment]
Now I am hitting a nil point deref
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x2c818f]

goroutine 1 [running]:
github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets.Attributes.toGenerated(...)
        C:/Users/yumeng/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/keyvault/azsecrets@v0.3.0/models.go:93
github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets.Properties.toGenerated({0xc000105200, 0xc00008a840, 0x0})
        C:/Users/yumeng/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/keyvault/azsecrets@v0.3.0/client.go:442 +0x8f
github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets.(*Client).UpdateSecretProperties(0xc000118150, {0x3b57f0, 0xc00011a010}, {0x344857, 0xa}, {0xc000105200, 0xc00008a840, 0x0}, 0x3292a0)
        C:/Users/yumeng/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/keyvault/azsecrets@v0.3.0/client.go:459 +0xd5
main.main()
        C:/working/go/kv-samples/src/main.go:48 +0x74c
```

https://github.com/Azure/azure-sdk-for-go/blob/88d611e9ded5369c62e0776a641d1e019ad22ecc/sdk/keyvault/azsecrets/models.go#L93
