### ISSUE TITLE
Panic in Future Done function

### ISSUE THREAD

**Issue by salmanbukhari** [Azure/azure-sdk-for-go#1695]
My code is as following
 ```
 routeTableClient := network.NewRouteTablesClient(m.Subscription)
	routeTableClient.Authorizer = m.Authenticator
	future, err := routeTableClient.CreateOrUpdate(context.Background(), resourceGroup, input.Name, routeTable)
	if err != nil {
		utils.Error.Println(err)
		return "", false
	} else {
		err = future.WaitForCompletion(m.Context, routeTableClient.Client)
		if err != nil {
			utils.Error.Println(err)
			return "", false
		}

```
I have checked the err returned from CreateOrUpdate and later on WaitForCompletion. This code works fine in success case but today a panic was called in this code. I checked everything all the fields are valid. The Panic was caused inside the WaitForCompletion. 

> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x117d0c2]

```
goroutine 16889 [running]:
panic(0x221e640, 0xc4200120a0)
        /var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_v1.7/src/runtime/panic.go:500 +0x1a1
cluster-manager/vendor/github.com/Azure/go-autorest/autorest/azure.(*Future).Done(0xc420a4b3b8, 0x37b5c20, 0xc420587700, 0x37b5c00, 0x0, 0x0)
        /var/jenkins_home/workspace/cluster-manager-azure/cluster-apps/src/cluster-manager/vendor/github.com/Azure/go-autorest/autorest/azure/async.go:79 +0xc2
cluster-manager/vendor/github.com/Azure/go-autorest/autorest/azure.Future.WaitForCompletion(0xc420726e10, 0xc4208d5710, 0x25bc70d, 0xe, 0xc420a5e820, 0xc3, 0xc420928ec6, 0x9, 0x0, 0x37c6a20, ...)
        /var/jenkins_home/workspace/cluster-manager-azure/cluster-apps/src/cluster-manager/vendor/github.com/Azure/go-autorest/autorest/azure/async.go:164 +0x138
cluster-manager/securityservicesmanager.CreateAzureRouteTableSDK(0xc4201aaa80, 0xc4209708c0, 0xe, 0xc420be5f00, 0xc, 0xc4208d5320, 0x86, 0xc420484200, 0x1, 0x4, ...)
        /var/jenkins_home/workspace/cluster-manager-azure/cluster-apps/src/cluster-manager/securityservicesmanager/azure_sdk_services.go:1443 +0x802
```

If there is no error in CreateOrUpdate how this is possible that future.Done is nil pointer reference? Am I missing some more validations? I reran and it worked fine. My service was crashed due to the panic and i donot want this to happen.

**Comment by salmanbukhari** [comment]
Sorry, it was my mistake. My colleague added some print statement in the SDK and it was caused due to that.
