### ISSUE TITLE
Test failure TestReceiver_CanCancelLinkCreation

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-go#18174]
```
2022-05-18T11:45:47.4618480Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2022-05-18T11:45:47.4620560Z 	panic: runtime error: invalid memory address or nil pointer dereference
2022-05-18T11:45:47.4622829Z [signal 0xc0000005 code=0x0 addr=0x18 pc=0x14d0475]
2022-05-18T11:45:47.4624981Z 
2022-05-18T11:45:47.4628121Z goroutine 1575 [running]:
2022-05-18T11:45:47.4630247Z testing.tRunner.func1.2({0x153f160, 0x19a69b0})
2022-05-18T11:45:47.4633771Z 	C:/hostedtoolcache/windows/go/1.18.0/x64/src/testing/testing.go:1389 +0x24e
2022-05-18T11:45:47.4635291Z testing.tRunner.func1()
2022-05-18T11:45:47.4638113Z 	C:/hostedtoolcache/windows/go/1.18.0/x64/src/testing/testing.go:1392 +0x39f
2022-05-18T11:45:47.4640112Z panic({0x153f160, 0x19a69b0})
2022-05-18T11:45:47.4642998Z 	C:/hostedtoolcache/windows/go/1.18.0/x64/src/runtime/panic.go:838 +0x207
2022-05-18T11:45:47.4645053Z github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus.TestReceiver_CanCancelLinkCreation(0xc00051cd00?)
2022-05-18T11:45:47.4646929Z 	D:/a/_work/1/s/sdk/messaging/azservicebus/receiver_unit_test.go:325 +0x1b5
2022-05-18T11:45:47.4648960Z testing.tRunner(0xc00051cea0, 0x160cfd8)
2022-05-18T11:45:47.4651089Z 	C:/hostedtoolcache/windows/go/1.18.0/x64/src/testing/testing.go:1439 +0x102
2022-05-18T11:45:47.4654236Z created by testing.(*T).Run
2022-05-18T11:45:47.4656809Z 	C:/hostedtoolcache/windows/go/1.18.0/x64/src/testing/testing.go:1486 +0x35f
2022-05-18T11:45:47.4659546Z FAIL	github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus	91.183s
```

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1576407&view=logs&j=b00d7691-30bb-5463-5d2e-705128f6b9cf&t=9bbb8036-2f2e-5985-8580-d91f37fbbc00

**Comment by richardpark-msft** [comment]
The panic() here is because we actually didn't get an error - we expected to, since it's being cancelled.

I remember thinking this test was probably a little dicey because of timing. I'll see what I can do to make it more reliable.
