### ISSUE TITLE
azblob UploadStream produces panic: send on closed channel if input stream has error

### ISSUE THREAD

**Issue by ncw** [Azure/azure-sdk-for-go#19612]
### Bug Report

If an error occurs on the input channel when using `Client.UploadStream` from `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob` then `UploadStream` panics in the background shortly **after** it returns the error.

Here is a 100% reliable reproducer - set `account` and `containerName` below and make sure your auth is in the environment.

```go
package main

import (
	"bytes"
	"context"
	"crypto/rand"
	"errors"
	"fmt"
	"io"
	"log"
	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
)

const (
	account       = "https://XXXXX.blob.core.windows.net/"
	containerName = "XXXX"
	blobName      = "test.bin"
)

// ErrorReader wraps an error to return on Read
type ErrorReader struct {
	Err error
}

// Read always returns the error
func (er ErrorReader) Read(p []byte) (n int, err error) {
	return 0, er.Err
}

func main() {
	// authenticate with Azure Active Directory
	// this picks up the az login credentials
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("auth failed: %v", err)
	}

	// create a client for the specified storage account
	client, err := azblob.NewClient(account, cred, nil)
	if err != nil {
		log.Fatalf("create client failed: %v", err)
	}

	var N int64 = 5 * 1024

	// Construct in so it reads N bytes then produce an error
	buf := make([]byte, N)
	_, _ = rand.Read(buf)
	in1 := bytes.NewReader(buf)
	er := &ErrorReader{Err: errors.New("potato")}
	in := io.MultiReader(in1, er)

	// It is necessary to pass in azblob.UploadStreamOptions to
	// trigger the bug.
	uploadStreamOptions := azblob.UploadStreamOptions{
		BlockSize:   4 * 1024 * 1024,
		Concurrency: 16,
	}

	fmt.Printf("Uploading blob %q, error after %d\n", blobName, N)

	// upload the file to the specified container with the specified blob name
	_, err = client.UploadStream(context.TODO(), containerName, blobName, in, &uploadStreamOptions)
	fmt.Printf("Result err=%v\n", err)

	// Note the panic happens in the background and we don't
	// always catch it unless we sleep here
	fmt.Printf("Sleeping to wait for the panic\n")
	time.Sleep(1 * time.Second)

	fmt.Printf("Panic not triggered\n")
}
```

This produces

```
Uploading blob "test.bin", error after 5120
Result err=potato
Sleeping to wait for the panic
panic: send on closed channel

goroutine 6 [running]:
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared.staticBuffer.Put(...)
	/home/ncw/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.5.1/internal/shared/transfer_manager.go:83
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob.(*copier).write(0xc000002000, {{0xc000200000, 0x400000, 0x400000}, {0xc00002a1e0, 0x58}, 0x1400})
	/home/ncw/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.5.1/blockblob/chunkwriting.go:179 +0x354
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob.(*copier).sendChunk.func1()
	/home/ncw/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.5.1/blockblob/chunkwriting.go:153 +0xc7
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared.NewStaticBuffer.func1()
	/home/ncw/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.5.1/internal/shared/transfer_manager.go:62 +0x3b
created by github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared.NewStaticBuffer
	/home/ncw/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.5.1/internal/shared/transfer_manager.go:60 +0xce
```

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
- SDK version: This reproduces on the latest release `v0.5.1` and `main` (`v0.5.2-0.20221123052627-63a8c23f3b78`)
- Specify the exact commit if possible: 63a8c23f3b78
- output of `go version`: `go version go1.19.1 linux/amd64`

See also: This is very similar or perhaps identical to the closed https://github.com/Azure/azure-sdk-for-go/issues/17109

**Comment by jhendrixMSFT** [comment]
The fix for this will be released in `v0.6.0`.
