### ISSUE TITLE
Test failed on Debian riscv64

### ISSUE THREAD

**Issue by yuzibo** [Azure/azure-sdk-for-go#20465]
### Bug Report

It seems that it failed with `github.com/Azure/azure-sdk-for-go/services/eventgrid/2018-01-01/eventgrid`
go version: `1.19.6-2` 

First sorry I messed up the bug report section above.

I am a Debian riscv porter and noticed the [golang-github-azure-azure-sdk-for-go](https://tracker.debian.org/pkg/golang-github-azure-azure-sdk-for-go) package was unable to build on riscv64 due to test failed:
```
# github.com/Azure/azure-sdk-for-go/services/eventgrid/2018-01-01/eventgrid
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x607a8]

runtime stack:
runtime.throw({0x8d2d90?, 0x3f00207646?})
        /usr/lib/go-1.19/src/runtime/panic.go:1047 +0x44 fp=0x3f900637b8 sp=0x3f90063790 pc=0x4626c
runtime.sigpanic()
        /usr/lib/go-1.19/src/runtime/signal_unix.go:819 +0x1e8 fp=0x3f900637e0 sp=0x3f900637b8 pc=0x5cb40
runtime.getStackMap(0x3f90063c28, 0x22f278?, 0xd?)
        /usr/lib/go-1.19/src/runtime/stack.go:1347 +0x2f0 fp=0x3f900638a0 sp=0x3f900637e8 pc=0x607a8
runtime.adjustframe(0x3f90063c28, 0x3f90063d08)
        /usr/lib/go-1.19/src/runtime/stack.go:667 +0x70 fp=0x3f90063928 sp=0x3f900638a0 pc=0x5f078
runtime.gentraceback(0x4000?, 0x1fc8?, 0x1bb48?, 0x3f900001a0, 0x0, 0x0, 0x7fffffff, 0x8e5628, 0xffffffffffffefe8?, 0x0)
        /usr/lib/go-1.19/src/runtime/traceback.go:345 +0x90c fp=0x3f90063c80 sp=0x3f90063928 pc=0x6b2ec
runtime.copystack(0x3f900001a0, 0x4000)
        /usr/lib/go-1.19/src/runtime/stack.go:932 +0x27c fp=0x3f90063e28 sp=0x3f90063c80 pc=0x5f7a4
runtime.newstack()
        /usr/lib/go-1.19/src/runtime/stack.go:1112 +0x354 fp=0x3f90063fd0 sp=0x3f90063e28 pc=0x5fbac
runtime.morestack()
        /usr/lib/go-1.19/src/runtime/asm_riscv64.s:204 +0x58 fp=0x3f90063fd8 sp=0x3f90063fd0 pc=0x74668

goroutine 1 [copystack]:
cmd/compile/internal/importer.(*importReader).byte(0x3f90490b40)
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:788 +0x10 fp=0x3f9042e330 sp=0x3f9042e330 pc=0x754858
cmd/compile/internal/importer.(*importReader).obj(0x3f90490b40, {0x3f9401f115, 0x7})
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:328 +0x48 fp=0x3f9042e4d8 sp=0x3f9042e330 pc=0x751860
cmd/compile/internal/importer.(*iimporter).doDecl(0x3f900b60a0, 0x3f904909b0, {0x3f9401f115, 0x7})
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:244 +0x180 fp=0x3f9042e530 sp=0x3f9042e4d8 pc=0x7510d0
cmd/compile/internal/importer.(*importReader).doType(0x3f90490af0, 0x0)
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:621 +0x434 fp=0x3f9042e718 sp=0x3f9042e530 pc=0x7536cc
cmd/compile/internal/importer.(*iimporter).typAt(0x3f900b60a0, 0x80, 0x0)
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:292 +0x170 fp=0x3f9042e768 sp=0x3f9042e718 pc=0x751700
cmd/compile/internal/importer.(*importReader).typ(0x3f90490aa0)
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:601 +0x44 fp=0x3f9042e788 sp=0x3f9042e768 pc=0x75319c
cmd/compile/internal/importer.(*importReader).param(0x3f90490aa0)
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:764 +0x54 fp=0x3f9042e7e0 sp=0x3f9042e788 pc=0x7545ec
cmd/compile/internal/importer.(*importReader).paramList(0x83d7c0?)
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:756 +0x6c fp=0x3f9042e820 sp=0x3f9042e7e0 pc=0x754504
cmd/compile/internal/importer.(*importReader).signature(0x3f90490aa0?, 0xa2ee20?, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:736 +0x8c fp=0x3f9042e898 sp=0x3f9042e820 pc=0x754314
cmd/compile/internal/importer.(*importReader).obj(0x3f90490aa0, {0x3f9401f568, 0xa})
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:347 +0xd4 fp=0x3f9042ea40 sp=0x3f9042e898 pc=0x7518ec
cmd/compile/internal/importer.(*iimporter).doDecl(0x3f900b60a0, 0x3f904909b0, {0x3f9401f568, 0xa})
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:244 +0x180 fp=0x3f9042ea98 sp=0x3f9042ea40 pc=0x7510d0
cmd/compile/internal/importer.ImportData(0x3f904908c0?, {0x3f9401f0bd, 0x2396}, {0x3f9049a021, 0x7})
        /usr/lib/go-1.19/src/cmd/compile/internal/importer/iimport.go:180 +0x844 fp=0x3f9042ee10 sp=0x3f9042ea98 pc=0x750afc
cmd/compile/internal/noder.readImportFile({0x3f9049a021?, 0x843a60?}, 0x3f900fa300, 0x1?, 0x3f9041cf30)
        /usr/lib/go-1.19/src/cmd/compile/internal/noder/import.go:255 +0x4a4 fp=0x3f9042efb8 sp=0x3f9042ee10 pc=0x761dfc
cmd/compile/internal/noder.(*gcimports).ImportFrom(0xd0?, {0x3f9049a021?, 0x3f90488720?}, {0x3f94032fc8?, 0xd0?}, 0x3f90052400?)
        /usr/lib/go-1.19/src/cmd/compile/internal/noder/import.go:45 +0x74 fp=0x3f9042efe8 sp=0x3f9042efb8 pc=0x760dec
cmd/compile/internal/types2.(*Checker).importPackage(0x3f90420000, {0x3f90480000?, 0x8aad3c?, 0x0?}, {0x3f9049a021, 0x7}, {0x3fe169f9d9, 0xc2})
        /usr/lib/go-1.19/src/cmd/compile/internal/types2/resolver.go:144 +0x17c fp=0x3f9042f0e0 sp=0x3f9042efe8 pc=0x7291c4
cmd/compile/internal/types2.(*Checker).collectObjects(0x3f90420000)
        /usr/lib/go-1.19/src/cmd/compile/internal/types2/resolver.go:253 +0xc0c fp=0x3f9042f688 sp=0x3f9042f0e0 pc=0x72a19c
cmd/compile/internal/types2.(*Checker).checkFiles(0x3f90420000, {0x3f9049c120, 0x4, 0x4})
        /usr/lib/go-1.19/src/cmd/compile/internal/types2/check.go:321 +0x130 fp=0x3f9042f6f8 sp=0x3f9042f688 pc=0x6fe5d0
cmd/compile/internal/types2.(*Checker).Files(...)
        /usr/lib/go-1.19/src/cmd/compile/internal/types2/check.go:299
cmd/compile/internal/types2.(*Config).Check(0x3f9048c030?, {0x3fe169f8f1?, 0x0?}, {0x3f9049c120, 0x4, 0x4}, 0x0?)
        /usr/lib/go-1.19/src/cmd/compile/internal/types2/api.go:416 +0xac fp=0x3f9042f740 sp=0x3f9042f6f8 pc=0x6f0aac
cmd/compile/internal/noder.checkFiles({0x3f90393d00, 0x4, 0x32000000010279c0?})
        /usr/lib/go-1.19/src/cmd/compile/internal/noder/irgen.go:64 +0x328 fp=0x3f9042f888 sp=0x3f9042f740 pc=0x763078
cmd/compile/internal/noder.check2({0x3f90393d00, 0x4, 0x4})
        /usr/lib/go-1.19/src/cmd/compile/internal/noder/irgen.go:77 +0x48 fp=0x3f9042f9a8 sp=0x3f9042f888 pc=0x7632f8
cmd/compile/internal/noder.LoadPackage({0x3f900a8110, 0x4, 0x5})
        /usr/lib/go-1.19/src/cmd/compile/internal/noder/noder.go:82 +0x398 fp=0x3f9042fad0 sp=0x3f9042f9a8 pc=0x766c70
cmd/compile/internal/gc.Main(0x8e47d8)
        /usr/lib/go-1.19/src/cmd/compile/internal/gc/main.go:189 +0xb08 fp=0x3f9042ff28 sp=0x3f9042fad0 pc=0x7c1750
main.main()
        /usr/lib/go-1.19/src/cmd/compile/main.go:57 +0xec fp=0x3f9042ff80 sp=0x3f9042ff28 pc=0x7e8734
runtime.main()
        /usr/lib/go-1.19/src/runtime/proc.go:250 +0x218 fp=0x3f9042ffd8 sp=0x3f9042ff80 pc=0x48898
runtime.goexit()
        /usr/lib/go-1.19/src/runtime/asm_riscv64.s:516 +0x4 fp=0x3f9042ffd8 sp=0x3f9042ffd8 pc=0x767b4

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go-1.19/src/runtime/proc.go:363 +0x110 fp=0x3f9004efb0 sp=0x3f9004ef98 pc=0x48c98
runtime.goparkunlock(...)
        /usr/lib/go-1.19/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/lib/go-1.19/src/runtime/proc.go:302 +0xb0 fp=0x3f9004efd8 sp=0x3f9004efb0 pc=0x48b20
runtime.goexit()
        /usr/lib/go-1.19/src/runtime/asm_riscv64.s:516 +0x4 fp=0x3f9004efd8 sp=0x3f9004efd8 pc=0x767b4
created by runtime.init.5
        /usr/lib/go-1.19/src/runtime/proc.go:290 +0x28

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go-1.19/src/runtime/proc.go:363 +0x110 fp=0x3f9004f798 sp=0x3f9004f780 pc=0x48c98
runtime.goparkunlock(...)
        /usr/lib/go-1.19/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/lib/go-1.19/src/runtime/mgcsweep.go:297 +0x114 fp=0x3f9004f7c8 sp=0x3f9004f798 pc=0x335cc
runtime.gcenable.func1()
        /usr/lib/go-1.19/src/runtime/mgc.go:178 +0x2c fp=0x3f9004f7d8 sp=0x3f9004f7c8 pc=0x27d74
runtime.goexit()
        /usr/lib/go-1.19/src/runtime/asm_riscv64.s:516 +0x4 fp=0x3f9004f7d8 sp=0x3f9004f7d8 pc=0x767b4
created by runtime.gcenable
        /usr/lib/go-1.19/src/runtime/mgc.go:178 +0x70

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x412e848000000000?)
        /usr/lib/go-1.19/src/runtime/proc.go:363 +0x110 fp=0x3f9004ff80 sp=0x3f9004ff68 pc=0x48c98
runtime.goparkunlock(...)
        /usr/lib/go-1.19/src/runtime/proc.go:369
runtime.(*scavengerState).park(0xfee560)
        /usr/lib/go-1.19/src/runtime/mgcscavenge.go:389 +0x68 fp=0x3f9004ffa8 sp=0x3f9004ff80 pc=0x314e8
runtime.bgscavenge(0x0?)
        /usr/lib/go-1.19/src/runtime/mgcscavenge.go:622 +0x6c fp=0x3f9004ffc8 sp=0x3f9004ffa8 pc=0x31a54
runtime.gcenable.func2()
        /usr/lib/go-1.19/src/runtime/mgc.go:179 +0x2c fp=0x3f9004ffd8 sp=0x3f9004ffc8 pc=0x27d14
runtime.goexit()
        /usr/lib/go-1.19/src/runtime/asm_riscv64.s:516 +0x4 fp=0x3f9004ffd8 sp=0x3f9004ffd8 pc=0x767b4
created by runtime.gcenable
        /usr/lib/go-1.19/src/runtime/mgc.go:179 +0xb0

goroutine 17 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go-1.19/src/runtime/proc.go:363 +0x110 fp=0x3f9004e5a8 sp=0x3f9004e590 pc=0x48c98
runtime.goparkunlock(...)
        /usr/lib/go-1.19/src/runtime/proc.go:369
runtime.runfinq()
        /usr/lib/go-1.19/src/runtime/mfinal.go:180 +0x110 fp=0x3f9004e7d8 sp=0x3f9004e5a8 pc=0x26f68
runtime.goexit()
        /usr/lib/go-1.19/src/runtime/asm_riscv64.s:516 +0x4 fp=0x3f9004e7d8 sp=0x3f9004e7d8 pc=0x767b4
created by runtime.createfing
        /usr/lib/go-1.19/src/runtime/mfinal.go:157 +0x64

goroutine 33 [GC worker (idle)]:
runtime.gopark(0x7672b8?, 0x3f90502000?, 0x8?, 0x73?, 0x3f90088540?)
        /usr/lib/go-1.19/src/runtime/proc.go:363 +0x110 fp=0x3f9004bf48 sp=0x3f9004bf30 pc=0x48c98
runtime.gcBgMarkWorker()
        /usr/lib/go-1.19/src/runtime/mgc.go:1235 +0x100 fp=0x3f9004bfd8 sp=0x3f9004bf48 pc=0x29f68
runtime.goexit()
        /usr/lib/go-1.19/src/runtime/asm_riscv64.s:516 +0x4 fp=0x3f9004bfd8 sp=0x3f9004bfd8 pc=0x767b4
created by runtime.gcBgMarkStartWorkers
        /usr/lib/go-1.19/src/runtime/mgc.go:1159 +0x2c

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x1408902ef69d5?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go-1.19/src/runtime/proc.go:363 +0x110 fp=0x3f9052a748 sp=0x3f9052a730 pc=0x48c98
runtime.gcBgMarkWorker()
        /usr/lib/go-1.19/src/runtime/mgc.go:1235 +0x100 fp=0x3f9052a7d8 sp=0x3f9052a748 pc=0x29f68
runtime.goexit()
        /usr/lib/go-1.19/src/runtime/asm_riscv64.s:516 +0x4 fp=0x3f9052a7d8 sp=0x3f9052a7d8 pc=0x767b4
created by runtime.gcBgMarkStartWorkers
        /usr/lib/go-1.19/src/runtime/mgc.go:1159 +0x2c

goroutine 49 [GC worker (idle)]:
runtime.gopark(0x102eb40?, 0x1?, 0x57?, 0xf5?, 0x3f90088480?)
        /usr/lib/go-1.19/src/runtime/proc.go:363 +0x110 fp=0x3f9004af48 sp=0x3f9004af30 pc=0x48c98
runtime.gcBgMarkWorker()
        /usr/lib/go-1.19/src/runtime/mgc.go:1235 +0x100 fp=0x3f9004afd8 sp=0x3f9004af48 pc=0x29f68
runtime.goexit()
        /usr/lib/go-1.19/src/runtime/asm_riscv64.s:516 +0x4 fp=0x3f9004afd8 sp=0x3f9004afd8 pc=0x767b4
created by runtime.gcBgMarkStartWorkers
        /usr/lib/go-1.19/src/runtime/mgc.go:1159 +0x2c

goroutine 50 [GC worker (idle)]:
runtime.gopark(0x1408902ef65ed?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go-1.19/src/runtime/proc.go:363 +0x110 fp=0x3f90526748 sp=0x3f90526730 pc=0x48c98
runtime.gcBgMarkWorker()
        /usr/lib/go-1.19/src/runtime/mgc.go:1235 +0x100 fp=0x3f905267d8 sp=0x3f90526748 pc=0x29f68
runtime.goexit()
        /usr/lib/go-1.19/src/runtime/asm_riscv64.s:516 +0x4 fp=0x3f905267d8 sp=0x3f905267d8 pc=0x767b4
created by runtime.gcBgMarkStartWorkers
        /usr/lib/go-1.19/src/runtime/mgc.go:1159 +0x2c

```
There is another error messages for other scenarios

```
goroutine 1 [running]:
cmd/internal/src.(*PosTable).Pos(...)
        /usr/lib/go-1.19/src/cmd/internal/src/xpos.go:153
cmd/internal/obj.(*Link).InnermostPos(...)
        /usr/lib/go-1.19/src/cmd/internal/obj/inl.go:108
cmd/internal/obj.(*Link).OutermostPos(0xa309c8?, {0x1a5624?, 0x0?})
        /usr/lib/go-1.19/src/cmd/internal/obj/inl.go:89 +0xfc
cmd/compile/internal/base.FmtPos({0x96a45a68?, 0x3f?})
        /usr/lib/go-1.19/src/cmd/compile/internal/base/print.go:63 +0x48
cmd/compile/internal/base.FatalfAt({0x61e55590?, 0x3f?}, {0x8b3caa, 0x9}, {0x3f5d2a3428, 0x1, 0x1})
        /usr/lib/go-1.19/src/cmd/compile/internal/base/print.go:215 +0x98
cmd/compile/internal/base.Fatalf(...)
        /usr/lib/go-1.19/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/gc.handlePanic()
        /usr/lib/go-1.19/src/cmd/compile/internal/gc/main.go:48 +0xa0
panic({0x87c400, 0x3f6c9f6de0})
        /usr/lib/go-1.19/src/runtime/panic.go:884 +0x1d8
cmd/internal/src.(*PosTable).Pos(...)
        /usr/lib/go-1.19/src/cmd/internal/src/xpos.go:153
cmd/internal/obj.(*Link).InnermostPos(...)
        /usr/lib/go-1.19/src/cmd/internal/obj/inl.go:108
cmd/internal/obj.(*Link).OutermostPos(0x20?, {0x880580?, 0x0?})
        /usr/lib/go-1.19/src/cmd/internal/obj/inl.go:89 +0xfc
cmd/compile/internal/base.FmtPos({0x2?, 0x0?})
        /usr/lib/go-1.19/src/cmd/compile/internal/base/print.go:63 +0x48
cmd/compile/internal/base.FatalfAt({0xa301e0?, 0x0?}, {0x8b8e79, 0xd}, {0x3f5d2a3818, 0x1, 0x1})
        /usr/lib/go-1.19/src/cmd/compile/internal/base/print.go:215 +0x98
cmd/compile/internal/base.Fatalf(...)
        /usr/lib/go-1.19/src/cmd/compile/internal/base/print.go:196
cmd/compile/internal/walk.(*orderState).stmt(0x3f61e58800, {0xa301e0?, 0x3f6f418150?})
        /usr/lib/go-1.19/src/cmd/compile/internal/walk/order.go:635 +0x2308
cmd/compile/internal/walk.(*orderState).stmtList(0xa301e0?, {0x3f6c09b0c0, 0x2, 0x2})
        /usr/lib/go-1.19/src/cmd/compile/internal/walk/order.go:401 +0xa4
cmd/compile/internal/walk.orderBlock(0x3f6101bcd0, 0x3f6d8ae720)
        /usr/lib/go-1.19/src/cmd/compile/internal/walk/order.go:490 +0xa8
cmd/compile/internal/walk.order(0x3f6101bcc0)
        /usr/lib/go-1.19/src/cmd/compile/internal/walk/order.go:67 +0xb8
cmd/compile/internal/walk.Walk(0x3f6101bcc0)
        /usr/lib/go-1.19/src/cmd/compile/internal/walk/walk.go:27 +0x60
cmd/compile/internal/gc.prepareFunc(0x3f6101bcc0)
        /usr/lib/go-1.19/src/cmd/compile/internal/gc/compile.go:92 +0x80
cmd/compile/internal/gc.enqueueFunc(0x3f6101bcc0)
        /usr/lib/go-1.19/src/cmd/compile/internal/gc/compile.go:66 +0x2a8
cmd/compile/internal/gc.Main(0x8e47d8)
        /usr/lib/go-1.19/src/cmd/compile/internal/gc/main.go:300 +0xf74
main.main()
        /usr/lib/go-1.19/src/cmd/compile/main.go:57 +0xec
```
Because the package was marked as [arch:all](https://buildd.debian.org/status/package.php?p=golang-github-azure-azure-sdk-for-go), So I suspect there is no meaning to be built on riscv64. But we have [debci](https://ci.debian.net/packages/g/golang-github-azure-azure-sdk-for-go/) that needs to rebuild it again on a real riscv64 machine so we got the error.

Any ideas about this? 

Thanks.

**Comment by jhendrixMSFT** [comment]
@yuzibo these look like panics in the compiler, your best bet is to follow up with the Go language team about this.

https://github.com/golang/go/issues
