### ISSUE TITLE
DownloadFile stuck

### ISSUE THREAD

**Issue by godelized** [Azure/azure-sdk-for-go#22426]
### Bug Report

- import path of package in question: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob`
- SDK version: `v1.3.0`,
- output of `go version`: `go version go1.22.0 linux/amd64`

> What happened?

One of our services was stuck on the `DownloadFile` method of the `azblob` blob client:

```
goroutine 1097782 [chan send, 702 minutes]:
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared.DoBatchTransfer({0x2036460, 0xc001a4de00}, 0xc0011b4240)
	/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.3.0/internal/shared/batch_transfer.go:64 +0x22b
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob.(*Client).downloadFile(0xc0031c6240, {0x2036460, 0xc001a4d6d0}, {0x2015fa0, 0xc001e798f8}, {{0x0, 0x0}, 0x400000, 0x0, 0x0, ...})
	/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.3.0/blob/client.go:520 +0xb1e
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob.(*Client).DownloadFile(0xc0031c6240, {0x2036460, 0xc001a4d6d0}, 0xc001e798f8, 0xc000f8bba0?)
	/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.3.0/blob/client.go:632 +0x2bf
...
```

Multiple goroutines are stuck, it seems that there is a deadlock:

```
goroutine 1097795 [chan send, 702 minutes]:
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob.(*Client).downloadFile.func4({0x2036460, 0xc0028d6000}, 0x17800000, 0x400000)
	/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.3.0/blob/client.go:545 +0x254
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared.DoBatchTransfer.func2()
	/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.3.0/internal/shared/batch_transfer.go:65 +0x2f
github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared.DoBatchTransfer.func1()
	/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.3.0/internal/shared/batch_transfer.go:50 +0x3e
created by github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/internal/shared.DoBatchTransfer in goroutine 1097782
	/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v1.3.0/internal/shared/batch_transfer.go:48 +0x192
```

The issue already happened when we upgraded to `1.2.1`: https://github.com/Azure/azure-sdk-for-go/issues/22156#issuecomment-1892315277. At that time we reverted to `1.1.0`.
We upgraded to `1.3.0` but the issue happened again, we had to revert again to `1.1.0`.

> What did you expect or want to happen?

Download converges.

> How can we reproduce it?

Not sure this can be easily reproduced.
We do use concurrency for our downloads.

> Anything we should know about your environment.

n/a.

**Comment by souravgupta-msft** [comment]
@godelized, we merged the fix in the main branch. We will keep you posted when we do the release.
