### ISSUE TITLE
Proper feedback on missing credentials

### ISSUE THREAD

**Issue by Dynom** [Azure/azure-sdk-for-go#686]
With a setup like:
```go
c, err := storage.NewBasicClient(
	os.Getenv("AZURE_STORAGE_ACCOUNT"),
	os.Getenv("AZURE_STORAGE_ACCESS_KEY"),
)
```

The following implementation produces a segfault when the environment values are empty strings:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x124b68f]

goroutine 1 [running]:
...vendor/github.com/Azure/azure-sdk-for-go/storage.Client.exec(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	...vendor/github.com/Azure/azure-sdk-for-go/storage/client.go:405 +0x23f
...vendor/github.com/Azure/azure-sdk-for-go/storage.(*Entity).Get(0xc4200ce820, 0x0, 0x12ed96c, 0x26, 0xc420101e50, 0x0, 0x0)
	...vendor/github.com/Azure/azure-sdk-for-go/storage/entity.go:96 +0x45b
main.main()
	...metrics.go:31 +0x460
exit status 2
```

Implemenation:
```go
package main

import (
	"fmt"

	"github.com/Azure/azure-sdk-for-go/storage"
)

func main() {
	var err error
	c, err := storage.NewBasicClient(
		os.Getenv("AZURE_STORAGE_ACCOUNT"),
		os.Getenv("AZURE_STORAGE_ACCESS_KEY"),
	)
	if err != nil {
		fmt.Errorf("Error %s", err)
	}

	tsc := c.GetTableService()
	table := tsc.GetTableReference("test")

	partitionKey := "foo"
	rowKey := "bar"
	entity := table.GetEntityReference(partitionKey, rowKey)
	err = entity.Insert(storage.MinimalMetadata, &storage.EntityOptions{})
	if err != nil {
		fmt.Printf("Error inserting %s.\n", err)
	} else {
		fmt.Println("All done!")
	}
}
```

I would expect instead that the `err` returned by the client factory indicates the problem.

**Comment by jhendrixMSFT** [comment]
Sorry for my late response.  I ran your sample against the latest SDK and indeed the error object returned from NewBasicClient() is not nil and contains a description of the issue.  Given this I'm going to close this issue.
